version: '3'

services:
  redis:
    image: redis:alpine

  processor:
    build:
      context: ./processor/
      dockerfile: Dockerfile
    command: gunicorn --bind '0.0.0.0:5000' app:app
    ports:
      - '5001:5000'
    environment:
      - FLASK_ENV=production
    depends_on:
      - 'redis'


